/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package operadores;

/**
 *
 * @author SENA
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLA1 = new javax.swing.JLabel();
        JLA2 = new javax.swing.JLabel();
        JLA3 = new javax.swing.JLabel();
        TXT1 = new javax.swing.JTextField();
        TXT2 = new javax.swing.JTextField();
        JLA4 = new javax.swing.JLabel();
        TXT3 = new javax.swing.JTextField();
        BNT1 = new javax.swing.JButton();
        BNT2 = new javax.swing.JButton();
        BNT3 = new javax.swing.JButton();
        BNT5 = new javax.swing.JButton();
        BNT8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(30, 40));
        jPanel1.setLayout(null);

        JLA1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLA1.setForeground(new java.awt.Color(0, 51, 51));
        JLA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLA1.setText("OPERACIONES CON NUMEROS");
        jPanel1.add(JLA1);
        JLA1.setBounds(180, 50, 310, 60);

        JLA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLA2.setText("Numero 1");
        jPanel1.add(JLA2);
        JLA2.setBounds(80, 130, 90, 20);

        JLA3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLA3.setText("Numero 2");
        jPanel1.add(JLA3);
        JLA3.setBounds(80, 180, 70, 20);

        TXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT1ActionPerformed(evt);
            }
        });
        jPanel1.add(TXT1);
        TXT1.setBounds(170, 130, 170, 30);

        TXT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT2ActionPerformed(evt);
            }
        });
        jPanel1.add(TXT2);
        TXT2.setBounds(170, 180, 170, 30);

        JLA4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLA4.setText("RESULTADO");
        jPanel1.add(JLA4);
        JLA4.setBounds(60, 240, 100, 20);

        TXT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT3ActionPerformed(evt);
            }
        });
        jPanel1.add(TXT3);
        TXT3.setBounds(170, 240, 170, 30);

        BNT1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT1.setText("SUMA");
        BNT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT1.setDoubleBuffered(true);
        BNT1.setInheritsPopupMenu(true);
        BNT1.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT1.setMinimumSize(null);
        BNT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT1ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT1);
        BNT1.setBounds(400, 130, 100, 30);

        BNT2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT2.setText("RAIZ CUADRADADA DE LA SUMA");
        BNT2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT2.setDoubleBuffered(true);
        BNT2.setInheritsPopupMenu(true);
        BNT2.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT2.setMinimumSize(null);
        BNT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT2ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT2);
        BNT2.setBounds(400, 290, 210, 30);

        BNT3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT3.setText("RESTAR");
        BNT3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT3.setDoubleBuffered(true);
        BNT3.setInheritsPopupMenu(true);
        BNT3.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT3.setMinimumSize(null);
        BNT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT3ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT3);
        BNT3.setBounds(400, 170, 110, 30);

        BNT5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT5.setText("MULTIPLICACION");
        BNT5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT5.setDoubleBuffered(true);
        BNT5.setInheritsPopupMenu(true);
        BNT5.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT5.setMinimumSize(null);
        BNT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT5ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT5);
        BNT5.setBounds(400, 210, 110, 30);

        BNT8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT8.setText("DIVISION");
        BNT8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT8.setDoubleBuffered(true);
        BNT8.setInheritsPopupMenu(true);
        BNT8.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT8.setMinimumSize(null);
        BNT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT8ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT8);
        BNT8.setBounds(400, 250, 110, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("TRIGONOMETRIA");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 350, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT1ActionPerformed

    private void TXT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT2ActionPerformed

    private void TXT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT3ActionPerformed

    private void BNT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT2ActionPerformed
        // TODO add your handling code here:
        int caja1, caja2,suma,resultado;
        caja1 = Integer.parseInt(TXT1.getText());
        caja2 = Integer.parseInt(TXT2.getText());
        resultado = caja1 + caja2;
        if(resultado<0){
            TXT3.setText("Valor negativo, debe ser un valor positivo");
        }else{
            double raiz = Math.sqrt(resultado);
            TXT3.setText(String.valueOf(raiz));
        }
        
        
    }//GEN-LAST:event_BNT2ActionPerformed

    private void BNT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT1ActionPerformed
        // TODO add your handling code here:
        int caja1,caja2,resultado;
        caja1 = Integer.parseInt(TXT1.getText());
        caja2 = Integer.parseInt(TXT2.getText());
        resultado = caja1 + caja2;
        
        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT1ActionPerformed

    private void BNT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT3ActionPerformed
        // TODO add your handling code here:
        int caja1,caja2,resultado;
        caja1 = Integer.parseInt(TXT1.getText());
        caja2 = Integer.parseInt(TXT2.getText());
        resultado = caja1 - caja2;
        
        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT3ActionPerformed

    private void BNT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT5ActionPerformed
        // TODO add your handling code here:
        int caja1,caja2,resultado;
        caja1 = Integer.parseInt(TXT1.getText());
        caja2 = Integer.parseInt(TXT2.getText());
        resultado = caja1 * caja2;
        
        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT5ActionPerformed

    private void BNT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT8ActionPerformed
        // TODO add your handling code here:
        double caja1,caja2,resultado;
        caja1 = Integer.parseInt(TXT1.getText());
        caja2 = Integer.parseInt(TXT2.getText());
        if(caja1 == 0 | caja2 == 0){
            TXT3.setText("ERROR");
        }else{
            resultado = caja1 / caja2;
            TXT3.setText(String.valueOf(resultado));
        }
        
    }//GEN-LAST:event_BNT8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Trigonometria abrir = new Trigonometria();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNT1;
    private javax.swing.JButton BNT2;
    private javax.swing.JButton BNT3;
    private javax.swing.JButton BNT5;
    private javax.swing.JButton BNT8;
    private javax.swing.JLabel JLA1;
    private javax.swing.JLabel JLA2;
    private javax.swing.JLabel JLA3;
    private javax.swing.JLabel JLA4;
    private javax.swing.JTextField TXT1;
    private javax.swing.JTextField TXT2;
    private javax.swing.JTextField TXT3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
