/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package operadores;

/**
 *
 * @author SENA
 */
public class Trigonometria extends javax.swing.JFrame {

    /**
     * Creates new form Trigonometria
     */
    public Trigonometria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLA1 = new javax.swing.JLabel();
        JLA2 = new javax.swing.JLabel();
        TXT1 = new javax.swing.JTextField();
        JLA4 = new javax.swing.JLabel();
        TXT3 = new javax.swing.JTextField();
        BNT4 = new javax.swing.JButton();
        BNT6 = new javax.swing.JButton();
        BNT7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BNT8 = new javax.swing.JButton();
        BNT9 = new javax.swing.JButton();
        BNT10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(30, 40));
        jPanel1.setMinimumSize(null);
        jPanel1.setLayout(null);

        JLA1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLA1.setForeground(new java.awt.Color(0, 51, 51));
        JLA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLA1.setText("CALCULADORA TRIGNOMETRIA");
        jPanel1.add(JLA1);
        JLA1.setBounds(180, 50, 310, 60);

        JLA2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLA2.setText("Angulo (Grados)");
        jPanel1.add(JLA2);
        JLA2.setBounds(50, 130, 120, 20);

        TXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT1ActionPerformed(evt);
            }
        });
        jPanel1.add(TXT1);
        TXT1.setBounds(170, 130, 170, 30);

        JLA4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLA4.setText("RESULTADO");
        jPanel1.add(JLA4);
        JLA4.setBounds(70, 180, 100, 20);

        TXT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT3ActionPerformed(evt);
            }
        });
        jPanel1.add(TXT3);
        TXT3.setBounds(170, 180, 170, 30);

        BNT4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT4.setText("SENO");
        BNT4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT4.setDoubleBuffered(true);
        BNT4.setInheritsPopupMenu(true);
        BNT4.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT4.setMinimumSize(null);
        BNT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT4ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT4);
        BNT4.setBounds(360, 130, 110, 30);

        BNT6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT6.setText("TANGENTE");
        BNT6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT6.setDoubleBuffered(true);
        BNT6.setInheritsPopupMenu(true);
        BNT6.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT6.setMinimumSize(null);
        BNT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT6ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT6);
        BNT6.setBounds(360, 180, 110, 30);

        BNT7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT7.setText("COSENO");
        BNT7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT7.setDoubleBuffered(true);
        BNT7.setInheritsPopupMenu(true);
        BNT7.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT7.setMinimumSize(null);
        BNT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT7ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT7);
        BNT7.setBounds(500, 130, 110, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("CALCULADORA");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 370, 140, 40);

        BNT8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT8.setText("SECANTE");
        BNT8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT8.setDoubleBuffered(true);
        BNT8.setInheritsPopupMenu(true);
        BNT8.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT8ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT8);
        BNT8.setBounds(500, 180, 110, 30);

        BNT9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT9.setText("COSECANTE");
        BNT9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT9.setDoubleBuffered(true);
        BNT9.setInheritsPopupMenu(true);
        BNT9.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT9ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT9);
        BNT9.setBounds(360, 230, 110, 30);

        BNT10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BNT10.setText("COTANGENTE");
        BNT10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BNT10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BNT10.setDoubleBuffered(true);
        BNT10.setInheritsPopupMenu(true);
        BNT10.setMaximumSize(new java.awt.Dimension(30, 40));
        BNT10.setSelected(true);
        BNT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNT10ActionPerformed(evt);
            }
        });
        jPanel1.add(BNT10);
        BNT10.setBounds(500, 230, 110, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT1ActionPerformed

    private void TXT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT3ActionPerformed

    private void BNT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT4ActionPerformed
        // TODO add your handling code here:
        double caja1,resultado,radian;
        caja1 = Integer.parseInt(TXT1.getText());
        radian = (caja1 * 3.1416)/180;
        resultado = Math.sin(radian);

        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT4ActionPerformed

    private void BNT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT6ActionPerformed
        // TODO add your handling code here:
        double caja1,resultado,radian;
        caja1 = Integer.parseInt(TXT1.getText());
        radian = (caja1 * 3.1416)/180;
        resultado = Math.tan(radian);

        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT6ActionPerformed

    private void BNT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT7ActionPerformed
        // TODO add your handling code here:
        double caja1,resultado,radian;
        caja1 = Integer.parseInt(TXT1.getText());
        radian = (caja1 * 3.1416)/180;
        resultado = Math.cos(radian);

        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Formulario abrir = new Formulario();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BNT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT8ActionPerformed
        // TODO add your handling code here:
        double caja1,resultado,radian;
        caja1 = Integer.parseInt(TXT1.getText());
        radian = (caja1 * 3.1416)/180;
        resultado = Math.asin(radian);
        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT8ActionPerformed

    private void BNT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT9ActionPerformed
        // TODO add your handling code here:
        double caja1,resultado,radian;
        caja1 = Integer.parseInt(TXT1.getText());
        radian = (caja1 * 3.1416)/180;
        resultado = Math.acos(radian);
        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT9ActionPerformed

    private void BNT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNT10ActionPerformed
        // TODO add your handling code here:
        double caja1,resultado,radian;
        caja1 = Integer.parseInt(TXT1.getText());
        radian = (caja1 * 3.1416)/180;
        resultado = Math.atan(radian);
        TXT3.setText(String.valueOf(resultado));
    }//GEN-LAST:event_BNT10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trigonometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trigonometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trigonometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trigonometria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trigonometria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNT10;
    private javax.swing.JButton BNT4;
    private javax.swing.JButton BNT6;
    private javax.swing.JButton BNT7;
    private javax.swing.JButton BNT8;
    private javax.swing.JButton BNT9;
    private javax.swing.JLabel JLA1;
    private javax.swing.JLabel JLA2;
    private javax.swing.JLabel JLA4;
    private javax.swing.JTextField TXT1;
    private javax.swing.JTextField TXT3;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
